#!/usr/bin/env ruby

require 'json'

lib = ARGV[0]
var = ARGV[1]
out = ARGV[1]

version_data = JSON.parse(`yarn list --pattern #{ARGV[0]} --json`)
version_number = version_data["data"]["trees"][0]["name"].split("@").last

cmd = "node_modules/.bin/browserify -r '#{lib}' -s '#{var}' | node_modules/.bin/uglifyjs > dist/#{out}.js --mangle --compress && echo '\\n// #{lib} #{version_number}\\nvar #{var} = module.exports;' >> dist/#{out}.js"

system cmd